# Generated by Django 4.2.21 on 2025-06-23 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvelapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readingguide',
            old_name='description',
            new_name='reading_list',
        ),
        migrations.AlterField(
            model_name='readingguide',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
