# Generated by Django 4.2.21 on 2025-07-16 03:48

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('marvelapp', '0002_rename_description_readingguide_reading_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingguide',
            name='reading_list',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
